config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: %i[new create destroy]
  resources :users, only: %i[create]
  resources :inputs, only: %i[new create destroy]
  get '/:query', to: 'inputs#new'
  root to: 'inputs#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/input.rb
class Input < ApplicationRecord
  validates :query, :result, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, uniqueness: true, presence: true
  has_many :inputs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  helper_method :current_user

  private

  def access_control
    redirect_to new_session_path unless session_exists? && current_user
  end

  def current_user
    User.find_by(id: get_session) unless get_session.nil?
  end

  def create_session(user_id)
    session[session_name] = user_id
  end

  def session_exists?
    session[session_name].present?
  end

  def get_session
    session[session_name]
  end

  def session_name
    :substringify_session_token
  end

end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController
  before_action :access_control, only: %i[new create destroy]
  
  def new
    @query = input_params[:query]
    @sub_string = nil
    unless @query.nil?
     @sub_string = get_longest_substring @query
    end
  end

  def create
    return if input_params[:query].nil? || input_params[:query].length == 0

    @input = current_user.inputs.build(input_params)
    @input.result = get_longest_substring input_params[:query]
    if @input.save
      redirect_to "/#{params[:query]}"
    else
      flash[:alert] = "Unable to store to database"
      redirect_to new_input_path
    end
  end

  private
  
  def get_longest_substring string
    string = string.gsub(/[^0-9a-z]/i, '')
    if string.nil? || string == ""
      return nil
    end
    str_to_char = string.chars
    map = {}
    first = 0
    last = 0
    diff = 0
    staring_index = 0
    ending_index = 0

    str_to_char.each_with_index do |char, i|
      if !map[char] || map[char] < first
        map[char] = i
        last = i
      else
        if diff < last - first
          diff = last - first
          staring_index = first
          ending_index = last
        end
        if map[char] >= first
          first = map[char] + 1
        else
          first = i
        end
        map[char] = i
        last = first = i
      end
      if diff < last - first
        staring_index = first
        ending_index = last
      end
    end

    return string [staring_index..ending_index]
  end

  def input_params
    params.permit(:query)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(username: session_params[:username])
    if @user&.authenticate(session_params[:password])
      create_session @user.id
      redirect_to root_path
    else
      flash[:alert] = "Username or password not found."
      render :new
    end
  end

  def destroy
    session.delete(:substringify_session_token)
    redirect_to root_path, alert: 'Your Logged out.'
  end

  def session_params
    params.permit(:username, :password, :password_confirmation)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.valid? && @user.save
      create_session @user.id
      redirect_to root_path
    else
      flash[:alert] = "Invalid input please sign in again."
      render 'sessions/new'
    end
  end

  private

  def user_params
    params.permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
  def result
    if @query && @sub_string
      out = render '/inputs/result'
      out.html_safe
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/input/new.html.erb
<section class="search-box-container">
  <div class="search-box">
    <button class="btn-search"><i class="fas fa-search"></i></button>
    <input type="text" class="input-search" placeholder="Type to Search...">
  </div>
</section>

app/views/inputs/_nav.html.erb
<nav class="navbar bg-theme w-100 mx-0 px-5">
  <a class="navbar-brand" href="#">
    <strong class="text-white display-6">Sub<em class="text-danger">[String]</em>ify</strong>
  </a>
  <%= link_to session_path(current_user.id), method: :delete, class: 'text-uppercase border-dark ml-md-2 mb-3 mb-md-0 text-decoration-none text-white' do%>
    <div class="d-flex flex-column align-items-center border border-white p-2">
      <small class="">Log out</small>
    </div>
  <%end%>
</nav>

app/views/inputs/_result.html.erb
<section class="row mt-5 pt-5">
  <table class="table table-striped table-light col-7 mx-auto">
    <thead>
      <tr>
        <th scope="col">Initial Input</th>
        <th scope="col">Longest non-repeating substring</th>
        <th scope="col">Substring Length</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="text-center"><%= @query%></td>
        <td class="text-center"><%= @sub_string %></td>
        <td class="text-center"><%= @sub_string.length%></td>
      </tr>
    </tbody>
  </table>
</section>

app/views/inputs/new.html.erb
<%= render partial: 'nav' %>
<section class="d-flex flex-column query-box-container bg-theme">
  <%= form_with url: inputs_path, method: :post do |form| %>
    <div class="query-box">
      <button type="submit" class="btn-search"><i class="fas fa-search"></i></button>
      <%= form.text_field :query, class: 'input-search', placeholder: 'Type your string input...' %>
    </div>
  <% end %>
  <%= result %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sub[String]ify</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid px-0 bg-white">
    <% if flash[:alert]%>
      <div class="alert alert-info alert-dismissible shadow-sm bg-white d-flex flex-column align-items-center col-7 mx-auto mt-2 py-1">
      <strong class="h6"><%= alert%></strong>
    <div>
      <a href="#" class="btn btn-light border mt-2 px-2" data-dismiss="alert" aria-label="close">Ok</a>
    </div>
    </div>
  <%end%>
    <%= yield %>
    
    <%= javascript_pack_tag 'session' %>
  </body>
</html>

app/views/users/_sign_up.html.erb
<div class="px-3 ">
  <div class="text-center border-bottom ">
    <h3>Sign up</h3>
  </div>
  <%= form_with url: users_path , class: 'form-horizontal' do %>
    <div class="form-group py-2">
      <%= label_tag :username, "User Name"%>
      <%= text_field_tag :username,"", placeholder: 'Your User Name here', class: 'form-control'%>
    </div>
    <div class="form-group py-2">
      <%= label_tag :password%>
      <%= password_field_tag :password,"",placeholder: 'Your password here', class: 'form-control'%>
    </div>
    <div class="form-group py-2">
      <%= label_tag :password_confirmation%>
      <%= password_field_tag :password_confirmation,"",placeholder: 'Retype Your password here', class: 'form-control'%>
    </div>
    <div class="form-group py-2 w-100 text-center">
      <%= submit_tag "Sign up", class: 'btn btn-info'%>
    </div>
  <%end%>

  <div class="d-flex flex-column align-items-center">
    <p>Or</p>
  </div>
</div>